server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./data/menu;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6380
      connect-timeout: 500ms
      timeout: 500ms
menu:
  cache-ttl: 10m
